decimal: 3
error_metrics:
- MAE
- MAPE
- RMSE
distance_metrics:
- euclidean
- cityblock
- braycurtis
- dtw
lag_days: 89
num_country_plot: 50
number_of_countries: 50
batch_size_lstm: 10
paths:
  bar_plot_path: ../results/running_results/content/Plots/barplot
  box_plot_path: ../results/running_results/content/Plots/boxplots
  csv_processed_path: ../results/running_results/content/csv_files/processed
  csv_processed_with_null_path: ../results/running_results/content/csv_files/processed_null
  data_path: ../data/covid_data_nov_30.csv
  exp1_inc_united_df_path: ../results/running_results/content/Result/exp1/united_dataframe/incremental
  exp1_path: ../results/running_results/content/Result/exp1
  exp1_runtime_path: ../results/running_results/content/Result/exp1/runtime
  exp1_static_united_df_path: ../results/running_results/content/Result/exp1/united_dataframe/static
  exp1_summary_path: ../results/running_results/content/Result/exp1/summary
  exp2_inc_united_df_path: ../results/running_results/content/Result/exp2/united_dataframe/incremental
  exp2_path: ../results/running_results/content/Result/exp2
  exp2_runtime_path: ../results/running_results/content/Result/exp2/runtime
  exp2_static_united_df_path: ../results/running_results/content/Result/exp2/united_dataframe/static
  exp2_summary_path: ../results/running_results/content/Result/exp2/summary
  exp3_path: ../results/running_results/content/Result/exp3
  exp3_distance_path: ../results/final_result_files/exp3/distances.pkl
  exp3_sorted_path: ../results/final_result_files/exp3
  exp3_summary_path: ../results/running_results/content/Result/exp3/summary
pretrain_days:
- 30
- 60
- 90
- 120
- 150
- 180
- 210
- 240
total_countries:
- Afghanistan
- Albania
- Algeria
- Andorra
- Angola
- Anguilla
- Antigua_and_Barbuda
- Argentina
- Armenia
- Aruba
- Australia
- Austria
- Azerbaijan
- Bahamas
- Bahrain
- Bangladesh
- Barbados
- Belarus
- Belgium
- Belize
- Benin
- Bermuda
- Bhutan
- Bolivia
- Bonaire, Saint Eustatius and Saba
- Bosnia_and_Herzegovina
- Botswana
- Brazil
- British_Virgin_Islands
- Brunei_Darussalam
- Bulgaria
- Burkina_Faso
- Burundi
- Cambodia
- Cameroon
- Canada
- Cape_Verde
- Cases_on_an_international_conveyance_Japan
- Cayman_Islands
- Central_African_Republic
- Chad
- Chile
- China
- Colombia
- Comoros
- Congo
- Costa_Rica
- Cote_dIvoire
- Croatia
- Cuba
- "Cura\xE7ao"
- Cyprus
- Czechia
- Democratic_Republic_of_the_Congo
- Denmark
- Djibouti
- Dominica
- Dominican_Republic
- Ecuador
- Egypt
- El_Salvador
- Equatorial_Guinea
- Eritrea
- Estonia
- Eswatini
- Ethiopia
- Falkland_Islands_(Malvinas)
- Faroe_Islands
- Fiji
- Finland
- France
- French_Polynesia
- Gabon
- Gambia
- Georgia
- Germany
- Ghana
- Gibraltar
- Greece
- Greenland
- Grenada
- Guam
- Guatemala
- Guernsey
- Guinea
- Guinea_Bissau
- Guyana
- Haiti
- Holy_See
- Honduras
- Hungary
- Iceland
- India
- Indonesia
- Iran
- Iraq
- Ireland
- Isle_of_Man
- Israel
- Italy
- Jamaica
- Japan
- Jersey
- Jordan
- Kazakhstan
- Kenya
- Kosovo
- Kuwait
- Kyrgyzstan
- Laos
- Latvia
- Lebanon
- Lesotho
- Liberia
- Libya
- Liechtenstein
- Lithuania
- Luxembourg
- Madagascar
- Malawi
- Malaysia
- Maldives
- Mali
- Malta
- Marshall_Islands
- Mauritania
- Mauritius
- Mexico
- Moldova
- Monaco
- Mongolia
- Montenegro
- Montserrat
- Morocco
- Mozambique
- Myanmar
- Namibia
- Nepal
- Netherlands
- New_Caledonia
- New_Zealand
- Nicaragua
- Niger
- Nigeria
- North_Macedonia
- Northern_Mariana_Islands
- Norway
- Oman
- Pakistan
- Palestine
- Panama
- Papua_New_Guinea
- Paraguay
- Peru
- Philippines
- Poland
- Portugal
- Puerto_Rico
- Qatar
- Romania
- Russia
- Rwanda
- Saint_Kitts_and_Nevis
- Saint_Lucia
- Saint_Vincent_and_the_Grenadines
- San_Marino
- Sao_Tome_and_Principe
- Saudi_Arabia
- Senegal
- Serbia
- Seychelles
- Sierra_Leone
- Singapore
- Sint_Maarten
- Slovakia
- Slovenia
- Solomon_Islands
- Somalia
- South_Africa
- South_Korea
- South_Sudan
- Spain
- Sri_Lanka
- Sudan
- Suriname
- Sweden
- Switzerland
- Syria
- Taiwan
- Tajikistan
- Thailand
- Timor_Leste
- Togo
- Trinidad_and_Tobago
- Tunisia
- Turkey
- Turks_and_Caicos_islands
- Uganda
- Ukraine
- United_Arab_Emirates
- United_Kingdom
- United_Republic_of_Tanzania
- United_States_of_America
- United_States_Virgin_Islands
- Uruguay
- Uzbekistan
- Vanuatu
- Venezuela
- Vietnam
- Wallis_and_Futuna
- Western_Sahara
- Yemen
- Zambia
- Zimbabwe
valid_countries:
- Algeria
- Australia
- Austria
- Bahrain
- Belgium
- Brazil
- Canada
- China
- Croatia
- Czechia
- Denmark
- Ecuador
- Egypt
- Estonia
- Finland
- France
- Georgia
- Germany
- Greece
- Iceland
- India
- Iran
- Iraq
- Ireland
- Israel
- Italy
- Japan
- Kuwait
- Lebanon
- Malaysia
- Mexico
- Netherlands
- Norway
- Oman
- Pakistan
- Philippines
- Qatar
- Romania
- Russia
- San_Marino
- Singapore
- South_Korea
- Spain
- Sweden
- Switzerland
- Taiwan
- United_Arab_Emirates
- United_Kingdom
- United_States_of_America
- Vietnam
